### ISSUE TITLE
@PostConstruct

### ISSUE THREAD

**Issue by mgoellnitz** [zsoltherpai/feather#2]
Just a small question: Is it true, that this part of JSR330 is simply not implemented yet?
I just started to add the web integration part of [dinistiq](http://mgoellnitz.github.io/dinistiq/) and the [modules stuff](https://github.com/mgoellnitz/tangram/tree/master/guicy) from the Google Guice integration of a web framework of mine, since you are using a similar modules approach, to obtain all the functionality I would need from a small DI solution.

Besides that missing bit, the JSR330 feather looks quite promising to get the whole thing up and running.

**Comment by zsoltherpai** [comment]
The @PostConstruct is part of JSR-250 not JSR-330 actually. In the case of Feather specifically, i think supporting it wouldn't add too much value. Let me explain:

Regarding dependency initialization, Feather does impose a few restrictions, it is more strict than most other implementations. It encourages the use of constructor injection. It does not inject to fields (only in a certain case, I'll come back to that), and does not support method injection. With these constraints in place - all the initialization done in a constructor or a @Provides method - there is no need for the notion of @PostConstruct.

The reason for these constraints is centralizing initialization of the dependencies. It's best practice in general with a number of benefits (like full control of initialization, immutable designs ,etc). There is one notable exception when injection is not doable this way: when the object instantiation is out of our control - eg done by a framework, like in the case of a junit test or an android activity. Feather supports field injections when triggered explicitly: feather.injectFields(target). When we do this, we can as well call an initialization method.

If you absolutely need implicit/transitive fields injections and method injections (cases when @PostConstruct is actually needed) you may want to chose another JSR-330 implementation. In my experience use of those features are - almost always - symptoms of design issues and can be avoided.

**Comment by mgoellnitz** [comment]
Thanks for the answer. True, it is part of JSR-250, but that JSR is just a set of annotations. My reading of it was from Part 2.5

> The PostConstruct annotation is used on a method that needs to be executed after dependency 
> injection is done to perform any initialization. ... This annotation MUST be supported on all classes
> that support dependency injection. ...

So, my understanding was, that implementations fulfilling JSR-330 (DI) would require this behaviour. I'm not quite sure if the JSRs can be read that independent of each other as you state.

Of course it might be possible to refactor implementations to deal with the constraints feather imposes. (Does it fulfil the TCK? Didn't check this...)
